//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialsPurchasePlan_SupplierAndMaterialSpecification
    {
        public int MaterialsPurchasePlanId { get; set; }
        public int SupplierId { get; set; }
        public int MaterialSpecificationId { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    
        public virtual MaterialSpecification MaterialSpecification { get; set; }
        public virtual MaterialsPurchasePlan MaterialsPurchasePlan { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
