//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int Id { get; set; }
        public int MaterialSpecification { get; set; }
        public int MaterialsPurchasePlanId { get; set; }
    
        public virtual MaterialSpecification MaterialSpecification1 { get; set; }
        public virtual MaterialsPurchasePlan MaterialsPurchasePlan { get; set; }
    }
}
