//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bakery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPlan_Product
    {
        public int ProductionPlanid { get; set; }
        public int ProductSpecificationId { get; set; }
        public int Quantity { get; set; }
    
        public virtual ProductionPlan ProductionPlan { get; set; }
        public virtual ProductSpecification ProductSpecification { get; set; }
    }
}
